### PR TITLE
Block orientation

### LINKED ISSUE #69: Orientation wrong on 8x32 module
Hi,

I've got the same problem as is being described over on [this arduino forum](https://forum.arduino.cc/index.php?topic=402656.0)

This diagram from there neatly illustrates the problem.
Led matrix with wrong orientation

The module looks like this.

8x32 led matrix

I guess I could break it apart and re-orientate it but that seems a little drastic.

Is there a simple workaround for this?

If not I'm happy to try and put together a pull request if you could give me some pointers.

### PR DESCRIPTION
**Pull request by rm-hull**
Fixes #69

### CODE REVIEW

**Comment by pmounsey** [comment]
I seem to get an error when passing "--block-orientation" argument.

pi@raspberrypi:~/scripts/luma.led_matrix $ sudo python examples/matrix_demo.py --block-orientation vertical

Traceback (most recent call last):
  File "examples/matrix_demo.py", line 86, in <module>
    demo(args.cascaded, args.block_orientation)
  File "examples/matrix_demo.py", line 19, in demo
    device = max7219(serial, cascaded=n or 1, block_orientation=block_orientation)
TypeError: __init__() got an unexpected keyword argument 'block_orientation'

**Comment by rm-hull** [comment]
@pmounsey - I've just released version 0.4.4 with this changed in it, so if you re-install from pypi with:

    $ sudo -H pip install --upgrade luma.led_matrix

and then try the demo again, hopefully it will work - let me know how you get on

**Comment by pmounsey** [comment]
Model:
Wangdd22 MAX7219 Dot Matrix Module Microcontroller 4 In 1 Display with 5pin Line 

Command:
$ sudo python examples/matrix_demo.py --cascaded 4 --block-orientation vertical

Video:
https://www.youtube.com/watch?v=4s9mpKIC8Eo

**Comment by OURLEDS** [comment]
The problem here is that is the following things to have in consideration:
Python or arduino

For Arduino users and MAX72xx library or MD parole here are the solutions taht works with the newest hadware (leds modules):

Just open the example, and if it is not working or mirrored ... just change the headers for one of this:
#define HARDWARE_TYPE MD_MAX72XX::FC16_HW 
#define HARDWARE_TYPE MD_MAX72XX::GENERIC_HW 
#define HARDWARE_TYPE MD_MAX72XX::ICSTATION_HW

You can just change it and compile with one of those lines each time ... or just take unplug one 8x8 module and check the name on the board below the chip .... if it says FC16 is FC16 ... if it is 1088AS like mine it should work with the ICSTATION﻿

If youa re using python no f.ck idea.
But for arduino don't get confused with downlaoding files and changingin the src files.h 
That is a VERY VERY VERY OUTDATED solution ...


THIS SOLUTION WORKS FOR DEVICES BOUGHTS in 2019 and using arduino 1.8.8 with the MAX72xx library of Oct 2018 version 3.0.2

If arduino is not 1.8.8 you bought the device long time ago or it is not a max7219  or if the max72xx library is not version 3.0.2 ... it probably won't work this simple change of headers ... 

All my day lost getting this work ... the job here is done ... Now I can fly away...

**Pull request merged**
