### PR TITLE
Add (approximations of) more characters for 7-segment display

### PR DESCRIPTION
**Pull request by emlyn**
I found some approximations of more characters and added them to the list. I've reordered them by ASCII code - most ASCII characters now have some representation. I think it's better than just showing an underscore, what do you think?

### CODE REVIEW

**Comment by emlyn** [comment]
Hi @rm-hull, any thoughts on this and #179?

**Comment by rm-hull** [comment]
Sorry I haven’t gotten around to this yet. It’s on my todo list - please bear with me

**Comment by thijstriemstra** [comment]
> please bear with me

https://www.youtube.com/watch?v=wAwJEH78l2I

**Comment by emlyn** [comment]
I just rebased onto the latest master so that it can merge cleanly again.

**Pull request merged**
