### PR TITLE
release: 1.7.0

### PR DESCRIPTION
**Pull request by thijstriemstra**
Can you also tag a new release after merging this?

### CODE REVIEW

**Review by rm-hull — APPROVED** [review]

**Comment by thijstriemstra** [comment]
@rm-hull 

> Can you also tag a new release after merging this?

And do this for each sub-project? I would love to do it myself but I don't have permission.

**Comment by thijstriemstra** [comment]
hi @rm-hull I hope I'm not bothering you when I ask for making new releases, but could you please take a look at it? I hope all is ok.

**Comment by rm-hull** [comment]
Hi sorry @thijstriemstra, too many plates spinning at the moment 

I will do this evening. Will also look into making you an admin in GitHub projects and pypi

**Comment by thijstriemstra** [comment]
thanks!

**Comment by rm-hull** [comment]
what's your username on pypi ?

**Comment by thijstriemstra** [comment]
https://pypi.org/user/collab/

**Comment by rm-hull** [comment]
https://pypi.org/project/luma.led-matrix/1.7.0/ released

**Comment by thijstriemstra** [comment]
@rm-hull can you also make a tag for the releases? I thought releases were automated by creating a tag..

**Pull request merged**
