### PR TITLE
remove redundant ws2812 package

### LINKED ISSUE #260: Installation on Raspberry Pi OS Lite (bullseye) aborts with an error
First of all thanks for all your effort! Your work is greatly appreciated!

I've been using the luma.led_matrix package for quite a while without any issues on an RPI 3B with Raspberry Pi OS Lite (**buster**).
Now I tried the latest Raspberry Pi OS Lite (**bullseye**) release (same hardware,  setup from scratch).
Unfortunately the installation of  luma.led_matrix package aborts with an error. Seems  there is a problem with ws2812.

Any ideas?

#### Type of Raspberry Pi
Raspberry Pi 3 Model B V1.2

#### Linux Kernel version
Linux 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
Raspbian GNU/Linux 11 (bullseye)

Python 3.9.2

#### Expected behaviour
successful installation with

`sudo python3 -m pip install --upgrade luma.led_matrix`

#### Actual behaviour

`sudo usermod -a -G spi,gpio pi`
`sudo apt install build-essential python3-dev python3-pip libfreetype6-dev libjpeg-dev libopenjp2-7 libtiff5`
`sudo -H pip install --upgrade --ignore-installed pip setuptools`

runs without error, but ...

`sudo python3 -m pip install --upgrade luma.led_matrix`

gives 

_ERROR: Failed building wheel for ws2812_

see details here: https://pastebin.com/raw/TRquDVmd

### PR DESCRIPTION
**Pull request by thijstriemstra**
See https://github.com/rm-hull/luma.led_matrix/issues/260#issuecomment-980800315

fixes #260

### CODE REVIEW

**Comment by thijstriemstra** [comment]
could you please take a look @rm-hull? this issue is reported on a daily basis by new users.

**Comment by rm-hull** [comment]
just wondering if the ws2812 pypi package is a peer dependency of rpi_ws281x .. I will try and dig out my unicornhat and give it a blast, and if it still works we can gladly remove it

**Comment by thijstriemstra** [comment]
doesn't look like it: https://github.com/jgarff/rpi_ws281x/blob/master/python/setup.py

**Comment by Gadgetoid** [comment]
rpi_ws2812 is a standalone port/binding of the rpi_ws281x C library.

ws2812 is a very old and forgotten port of https://github.com/626Pilot/RaspberryPi-NeoPixel-WS2812

ws2812 is safe to drop.

I should probably do something with ws2812...

**Review by Gadgetoid — APPROVED** [review]

**Comment by thijstriemstra** [comment]
can I help with something @rm-hull?

**Pull request merged**
