### PR TITLE
namespace fix

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes https://github.com/rm-hull/luma.core/issues/164

### CODE REVIEW

**Comment by thijstriemstra** [comment]
the build is failing because a new luma.core release is needed (I suspect...), see core PR https://github.com/rm-hull/luma.core/pull/165

**Comment by thijstriemstra** [comment]
Let me check the setuptools version, there's a py3.6 specific setuptools issue: https://github.com/pypa/setuptools/pull/1402

**Comment by rm-hull** [comment]
ok, let me release a new luma.core ... 1.12.0 do you think?

**Comment by thijstriemstra** [comment]
sounds good

**Comment by thijstriemstra** [comment]
ran tests locally on py3.7.3 and no failures there.

**Comment by rm-hull** [comment]
luma.core 1.12.0 released: https://pypi.org/project/luma.core/1.12.0/

**Comment by thijstriemstra** [comment]
found a fix (upgrading pip and setuptools) for python 3.6, but i think this means setuptools 40.0 and newer is now required for python 3.6. the docs should probably mention this, i'll update them now.

**Pull request merged**
