### PR TITLE
Use github actions to publish to pypi

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ping @rm-hull

**Review by rm-hull — APPROVED** [review]

**Comment by rm-hull** [comment]
done
apologies ... been monstrously busy lately

**Comment by rm-hull** [comment]
tokens added too btw

**Comment by thijstriemstra** [comment]
thanks! can you also put out a new release, some test related stuff and packaging has changed.

**Pull request merged**
