### PR TITLE
Add readthedocs configuration

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by rm-hull** [comment]
Failed: https://readthedocs.org/projects/luma-led-matrix/builds/5081789/

**Comment by thijstriemstra** [comment]
@rm-hull looks like python3.5 only: https://github.com/pypa/setuptools/issues/885#issuecomment-266490932 which what the rtd builder uses. If I can't work around the issue I'll let it use py2.7.

**Comment by thijstriemstra** [comment]
hopefully this worked @rm-hull?

**Comment by rm-hull** [comment]
* https://readthedocs.org/projects/luma-led-matrix/builds/5081838/
* http://luma-led-matrix.readthedocs.io/en/rtd-update/

It was successful, but look at http://luma-led-matrix.readthedocs.io/en/rtd-update/api-documentation.html vs http://luma-led-matrix.readthedocs.io/en/latest/api-documentation.html - no class diagram...

What happens if the following is added to the setup:

```
    extras_require={
         'docs': [
             'sphinx >= 1.5.1',
             'luma.core>=0.3.1',
             'luma.emulator'
        ]
    },
```

Definitely heading in the right direction with all this stuff :-)

**Comment by thijstriemstra** [comment]
I'd really like to prevent what you're suggesting but I agree it will probably fix it. Investigating.

**Comment by thijstriemstra** [comment]
@rm-hull it looks like it's because of this (error)[https://readthedocs.org/projects/luma-led-matrix/builds/5081838/]:

```
WARNING: intersphinx inventory 'https://luma-core.readthedocs.io/en/latest/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError()
```

If it can't read the inventory, it won't be able to build a diagram.

**Comment by thijstriemstra** [comment]
@rm-hull with what Sphinx version was the latest on luma-core rtd build?

**Comment by rm-hull** [comment]
http://readthedocs.org/projects/luma-core/builds/5081841/

Looks like 1.3.5

**Comment by thijstriemstra** [comment]
@rm-hull why is luma.core part of the luma.led_matrix api documentation? I shouldn't see these classes on http://luma-led-matrix.readthedocs.io/en/latest/api-documentation.html but I also see them locally.

**Comment by rm-hull** [comment]
I think luma.core is part of the docs for two reasons 
1. so that the class diagram shows the relevant class hierarchy
2. all the relevant are available in one place

**Comment by thijstriemstra** [comment]
When you click on the base class (of device for example) it takes you to the core documentation. We should not have to maintain api listings in 5 or more projects.. We can always add some categories like exceptions and link to the core exceptions but we can't keep 5 versions of core synced across projects, it'll always be out of date (until it's build again).

**Comment by rm-hull** [comment]
hmmmm... take your point, but comparing http://luma-led-matrix.readthedocs.io/en/rtd-update/api-documentation.html vs. http://luma-led-matrix.readthedocs.io/en/latest/api-documentation.html, the latter is easier to discover new classes.

Taking a step backwards, I wonder if it would be better to introduce a new repo, luma.docs, which is a fusion of all API docs from all repos, and one definitive set of usage & install instructions ... ?

**Comment by thijstriemstra** [comment]
If you use this [tool](https://gist.github.com/epc/4118456) it gives a ValueError for a local Sphinx 1.5.3 build of core, e.g.:

```
$ python2.7 inventory.py --file ../../luma.core/doc/_build/html/objects.inv
Traceback (most recent call last):
  File "inventory.py", line 139, in <module>
    fetch_data(url,inv)
  File "inventory.py", line 102, in fetch_data
    invdata = read_inventory_v2(f, url, join)
  File "/home/thijs/.virtualenvs/test/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.py", line 80, in read_inventory_v2
    raise ValueError
ValueError
```

And also for the remote one:

```
$ python2.7 inventory.py --url https://luma-core.readthedocs.io/en/latest/objects.inv
```

And the same for the rtd-update:

```
$ python2.7 inventory.py --url https://luma-led-matrix.readthedocs.io/en/rtd-update/objects.inv
URL resolved to: https://luma-led-matrix.readthedocs.io/en/rtd-update/objects.inv
 objects.inv written to: /tmp/tmp7rKFWP
Using: https://luma-led-matrix.readthedocs.io/en/rtd-update/objects.inv as base HREF
Traceback (most recent call last):
  File "inventory.py", line 153, in <module>
    fetch_data(url,f.name)
  File "inventory.py", line 102, in fetch_data
    invdata = read_inventory_v2(f, url, join)
  File "/home/thijs/.virtualenvs/test/local/lib/python2.7/site-packages/sphinx/ext/intersphinx.py", line 80, in read_inventory_v2
    raise ValueError
ValueError
```

**Comment by thijstriemstra** [comment]
> Taking a step backwards, I wonder if it would be better to introduce a new repo, luma.docs, which is a fusion of all API docs from all repos, and one definitive set of usage & install instructions ... ?

This is maybe not a bad idea! Let's fix this intersphinx thing, and then merge towards a single doc repo. But I personally think it's much better to read now, and with the update stuff, this is the only way to maintain.

**Comment by thijstriemstra** [comment]
There's actually a better command for inspection.

Getting same with Sphinx 1.5.1, 1.5.2 and 1.5.3:
```
$ python -m sphinx.ext.intersphinx _build/html/objects.inv 
intersphinx inventory '_build/html/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError()
```

**Comment by thijstriemstra** [comment]
I think it's a Sphinx issue and added some comments here: https://github.com/sphinx-doc/sphinx/issues/3234 These PRs are blocked till then :-/

**Comment by thijstriemstra** [comment]
ps. are you able to reproduce it @rm-hull?

**Comment by rm-hull** [comment]
Will give it a try

**Comment by thijstriemstra** [comment]
If you still want to try to reproduce, follow the steps in https://github.com/sphinx-doc/sphinx/issues/3488

**Comment by rm-hull** [comment]
Good that you raised an issue, not so good that there 559 open ones before yours

**Comment by thijstriemstra** [comment]
@rm-hull if you can force a new build for this branch then it should grab the intersphinx for luma.core and correctly render the graph.

**Comment by rm-hull** [comment]
https://readthedocs.org/projects/luma-led-matrix/builds/5091913/

**Comment by thijstriemstra** [comment]
Well, it did read in the core intersphinx:

```
loading intersphinx inventory from https://luma-core.readthedocs.io/en/latest/objects.inv...
```
But no diagram, meh :-/

**Comment by rm-hull** [comment]
On the bright side, the base object links work now though :-)

**Comment by thijstriemstra** [comment]
Yep!

**Comment by rm-hull** [comment]
Going back to what we mentioned the other day:

```
    extras_require={
         'docs': [
             'sphinx >= 1.5.1',
             'luma.core>=0.3.1',
             'luma.emulator'
        ]
    },
```

worth trying it, to see if that will bring the inheritance diagram back?

**Comment by thijstriemstra** [comment]
I think the logs will show that it's already installed, let me check.

**Comment by thijstriemstra** [comment]
But luma.emulator is missing.

**Comment by thijstriemstra** [comment]
Ha it fixed it! @rm-hull can you live without the emulator inheritance in the diagram(s) until we have a doc project setup? Or you want to add luma.emulator for the docs dependencies?

**Comment by rm-hull** [comment]
Think we can live without the emulator for the time being.

**Comment by thijstriemstra** [comment]
Alright, if you can approve the PRs than I'll fix that last thing and merge.

**Pull request merged**
